# Generated by Django 4.2 on 2026-03-23 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('route_type', models.CharField(choices=[('college_to_city', 'College to City'), ('city_to_college', 'City to College')], max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('total_seats', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('fare', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['route_type', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateField()),
                ('num_tickets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('used', 'Used'), ('expired', 'Expired')], default='confirmed', max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bus.busroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
                'unique_together': {('user', 'travel_date', 'route')},
            },
        ),
    ]
