# Generated by Django 4.2 on 2026-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
